### ISSUE TITLE
NSGenericException: AVCaptureSession

### ISSUE THREAD

**Issue by blacktorch** [aws-amplify/amplify-ui-swift-liveness#102] opened 2024-02-02 22:42 UTC
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'

**Comment by phantumcode** [comment] 2024-02-05 17:24
@blacktorch Thanks for submitting the issue.  Can you provide additional details and steps to reproduce?  What version is this issue observed in? There is a similar issue that has been fixed starting with version [1.2.2](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.2.2)

**Comment by ple-d** [comment] 2024-02-07 09:39
This issue affected iOS 17.2.1 and 17.3.0 according to our crashlytics

**Comment by phantumcode** [comment] 2024-02-12 18:42
@blacktorch Is this still an issue? Are you observing this issue in version 1.2.2 or greater? The latest version 1.2.5

**Comment by ple-d** [comment] 2024-02-19 02:52
@phantumcode suddenly, I found this issue on version 1.2.3. iOS 17.3.1. Here's log. 
Maybe I'm doing something wrong, but I'll really appreciate, if you try to reproduce it.
`warning: Module "/Users/****/Library/Developer/Xcode/iOS DeviceSupport/iPhone14,5 17.3.1 (21D61)/Symbols/usr/lib/libobjc.A.dylib" uses triple "arm64e-apple-ios17.3.0", which is not compatible with the target triple "arm64-apple-ios14.0.0". Enabling per-module Swift scratch context.
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'

**Comment by MRJYL** [comment] 2024-03-01 03:40
it still crash in version 1.2.2

**Comment by jerearaujo03** [comment] 2024-03-01 21:06
I'm getting this issue too

**Comment by MRJYL** [comment] 2024-03-07 09:50
> @MRJYL @jerearaujo03 Can you provide additional information to help reproduce this issue? What platform (native iOS, flutter, etc), what iOS version and device ? What the steps to reproduce?
This just part of it

![image](https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/12264960/8dcaa03c-99aa-4a1b-bf54-aa65d0111afe)

**Comment by thisisabhash** [comment] 2024-03-15 16:54
We have added some improvements in this branch [fix/avcapture-session](https://github.com/aws-amplify/amplify-ui-swift-liveness/tree/fix/avcapture-session)
Could you please check out the branch to see if it helps with your issue?

**Comment by phantumcode** [comment] 2024-04-11 17:40
Fixed in latest version [1.2.9](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.2.9)

**Closed by phantumcode** 2024-04-11 17:40 UTC
Labels: bug, closing-soon
