### ISSUE TITLE
crash due to aws_event_stream_rpc_server_continuation_send_message

### ISSUE THREAD

**Issue by MRJYL** [aws-amplify/amplify-ui-swift-liveness#111] opened 2024-03-01 03:48 UTC
### Describe the bug

We found some crashs when trying  to start vefirication, but there don't have detailed information @phantumcode 

![screenshot-20240301-114537](https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/12264960/d03cef26-d102-4caa-856d-d352a23e344f)

**Comment by phantumcode** [comment] 2024-03-01 16:20
@MRJYL Thanks for submitting the issue.  Can you provide any details on how to reproduce the crash or how the crash was captured to help us reproduce and troubleshoot the issue?

**Comment by MRJYL** [comment] 2024-03-07 09:33
The crash occurred when the user reported an error in the SDK callback and tried to retry the process。 I can't reproduce it reliably

**Comment by thisisabhash** [comment] 2024-03-15 16:55
We have added some improvements in this branch [fix/avcapture-session](https://github.com/aws-amplify/amplify-ui-swift-liveness/tree/fix/avcapture-session)
Could you please check out the branch to see if it helps with your issue?

**Comment by phantumcode** [comment] 2024-03-18 14:43
@MRJYL Can you provide more context here.  Based on the crash log, the crash is occurring in `AWSLivenessSDK` which is not our code.  Did you create a wrapper around our library and called it `AWSLivenessSDK`? what exactly is happening in the wrapper that's calling `aws_event_stream_rpc_server_continuation_send_message` ?  This seems to be calling into the AWS Common Runtime, which our library does not call.

**Comment by phantumcode** [comment] 2024-03-18 15:55
Closing this issue as the crash is occurring outside of Liveness library code.

**Closed by phantumcode** 2024-03-18 15:55 UTC
Labels: bug
