### ISSUE TITLE
Race condition with captureSession

### ISSUE THREAD

**Issue by ntnmrndn** [aws-amplify/amplify-ui-swift-liveness#74] opened 2023-11-13 08:15 UTC
```
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'
*** First throw call stack:
(0x1919c25e0 0x189ccbc00 0x1adbf0254 0x1162f4ff0 0x105ec5974 0x105ec59bc 0x116950f50 0x116952b34 0x11695564c 0x116966cd8 0x1169676cc 0x1faabe928 0x1faabea04)
libc++abi: terminating due to uncaught exception of type NSException
```

```
        DispatchQueue.global().async {
            captureSession.startRunning()
        }
```

Dismissing and presenting the capture session fast enough will result in race conditions around the capture session.

**Comment by phantumcode** [comment] 2023-11-16 19:02
@ntnmrndn Thank you for submitting the issue.  We'll investigate further and provide a fix soon.

**Comment by phantumcode** [comment] 2023-12-05 17:10
Closing this as a duplicate of #68

**Closed by phantumcode** 2023-12-05 17:10 UTC
Labels: bug, investigating
