### ISSUE TITLE
Crash with NSInternalInconsistencyException 

### ISSUE THREAD

**Issue by ntnmrndn** [aws-amplify/amplify-ui-swift-liveness#81] opened 2023-11-24 07:44 UTC
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) before appending pixel buffers'

This happened when retrying again after a a liveness verification froze before timing out. 

Might be related: https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/74#issue-1990100117

**Comment by phantumcode** [comment] 2023-11-30 16:24
@ntnmrndn Thanks for submitting the issue, we'll investigate and provide a fix soon.

**Comment by phantumcode** [comment] 2023-12-05 17:10
Closing this as a duplicate of #68

**Closed by phantumcode** 2023-12-05 17:10 UTC
Labels: bug
